# -*- coding: utf-8 -*-
"""date_initializing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1js3WhtUmSkKiHmYeOzyU0Vl9me1DSctK
"""

import datetime

def date():
  dates=[]
  month=[]
  day=[]
  year=[]
  i=1
  today = datetime.date.today()
  while i<=7:
    listdates = today - datetime.timedelta(days=i)
    dates.append(listdates)
    month.append(listdates.month)
    day.append(listdates.day)
    year.append(listdates.year)
    i= i+1
  return dates, month, day, year